language: python
python:
  - "2.7"
  - "3.6"
sudo: false
install:
 - mkdir -p buildout-cache/eggs
 - mkdir -p buildout-cache/downloads
 - python bootstrap.py
 - ./bin/buildout
script:
 - ./bin/test -m birdhousebuilder.recipe.conda
 - flake8
