language: python
python:
  - "2.7"
  - "3.5"
sudo: false
matrix:
  allow_failures:
    - python: 3.5
install:
 - mkdir -p buildout-cache/eggs
 - mkdir -p buildout-cache/downloads
 - pip install --upgrade setuptools
 - pip install --upgrade zc.buildout
 - buildout bootstrap
 - ./bin/buildout
script:
 - ./bin/test -m birdhousebuilder.recipe.conda

